### ISSUE TITLE
Birt WAR not deployed

### ISSUE THREAD

**Issue by zhex900** [cdorde/mybirt#1]
Hi,

I am trying to use your birt container. 
docker run --name birtviewer -d --restart=always -e VIRTUAL_HOST=birtreport.orocampus.tk -p 8888:8080 -v ~/birt:/usr/local/tomcat/webapps/birt/reports cdorde/mybirt

birtreport.orocampus.tk:8888/birt returns HTTP Status 404

This is the error message in cat logs/catalina.2017-02-08.log 
08-Feb-2017 12:52:52.534 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/birt]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:315)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)
	at java.util.jar.JarFile.getInputStream(JarFile.java:415)
	at org.apache.catalina.webresources.AbstractSingleArchiveResource.getJarInputStreamWrapper(AbstractSingleArchiveResource.java:39)
	at org.apache.catalina.webresources.AbstractArchiveResource.doGetInputStream(AbstractArchiveResource.java:230)
	at org.apache.catalina.webresources.AbstractResource.getInputStream(AbstractResource.java:93)
	at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:152)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5122)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more

08-Feb-2017 12:52:52.541 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /usr/local/tomcat/webapps/birt.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/birt]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zhex900** [comment]
I find the problem. This is a bug reported in https://bugs.eclipse.org/bugs/show_bug.cgi?id=497356

**Comment by StaticSpark** [comment]
Same Issue 
Java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

**Comment by cdorde** [comment]
Old one. With new version of JAVA SDK (8+) problem does not exists.
